final Map<String, String> questions = {
  "What is the capital of France?": "Paris",
  "What is the capital of Japan?": "Tokyo",
  "What is the capital of Brazil?": "Brasília",
  "What is the capital of Germany?": "Berlin",
  "What is the capital of Italy?": "Rome",
  "What is the capital of Canada?": "Ottawa",
  "What is the capital of Australia?": "Canberra",
  "What is the capital of Russia?": "Moscow",
  "What is the capital of China?": "Beijing",
  "What is the capital of India?": "New Delhi",
  "What is the capital of Spain?": "Madrid",
  "What is the capital of Egypt?": "Cairo",
  "What is the capital of Turkey?": "Ankara",
  "What is the capital of South Africa?": "Pretoria",
  "What is the capital of Saudi Arabia?": "Riyadh",
  "What is the capital of Mexico?": "Mexico City",
  "What is the capital of South Korea?": "Seoul",
  "What is the capital of United Kingdom?": "London",
  "What is the capital of Argentina?": "Buenos Aires",
  "What is the capital of Greece?": "Athens",
  "What is the capital of Lebanon?": "Beirut",
  "What is the capital of the United States?": "Washington, D.C.",
  "What is the capital of Sweden?": "Stockholm",
  "What is the capital of Norway?": "Oslo",
  "What is the capital of Kenya?": "Nairobi",
  "What is the capital of Thailand?": "Bangkok",
};
